CREATE TABLE COUNTRY
(
  ID   BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_12D499B0_8A27_44C9_B88F_76230FDF695D) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  CODE VARCHAR(255)
);
CREATE UNIQUE INDEX UK_5S4PTNUQTD24D4P9AU2RV53QM_INDEX_6
  ON COUNTRY (CODE);
CREATE TABLE CURRENCY
(
  ID            BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_58989CC5_B2C3_45EF_8159_F985ACE2AC38) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  CODE          VARCHAR(255),
  EXCHANGE_RATE DOUBLE
);
CREATE UNIQUE INDEX UK_H84PD2RTR12ISNIFNJ655RKRA_INDEX_5
  ON CURRENCY (CODE);
CREATE TABLE PRODUCT
(
  ID          BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_A2122776_3A68_459F_AA96_7F9BC186FC30) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  PRICE       DOUBLE,
  CURRENCY_ID BIGINT                                                                                                                 NOT NULL,
  CONSTRAINT FKJS3QD4L0EBV5A0JFO7V59IMBN FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY (ID)
);
CREATE TABLE SALE
(
  ID          BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_0A805404_B28D_43BC_94DF_918A065AE97C) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  END_TIME    TIMESTAMP,
  ITEMS_LEFT  INTEGER,
  START_TIME  TIMESTAMP,
  TOTAL_ITEMS INTEGER,
  COUNTRY_ID  BIGINT,
  PRODUCT_ID  BIGINT                                                                                                                 NOT NULL,
  CONSTRAINT FKDF71JEAXL0EQRH1AB0WIET7JJ FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (ID),
  CONSTRAINT FKONRCQWF09U6SPB6TY6SH11JH5 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);
CREATE TABLE USER
(
  ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_24D2D938_C022_43BF_9D62_C0003B650D74) AUTO_INCREMENT PRIMARY KEY NOT NULL
);
CREATE TABLE WALLET
(
  ID          BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_D92A5977_F895_466D_8DBB_AD359A38D020) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  BALANCE     DOUBLE,
  CURRENCY_ID BIGINT,
  USER_ID     BIGINT                                                                                                                 NOT NULL,
  CONSTRAINT FKHWM501SBBOC7ALNO0GI3CFA86 FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY (ID),
  CONSTRAINT FKBS4OGWIKNSUP4RPW8D47QW9DX FOREIGN KEY (USER_ID) REFERENCES USER (ID)
)
CREATE TABLE COUNTRY
(
  ID   BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_12D499B0_8A27_44C9_B88F_76230FDF695D) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  CODE VARCHAR(255)
);
CREATE UNIQUE INDEX UK_5S4PTNUQTD24D4P9AU2RV53QM_INDEX_6
  ON COUNTRY (CODE);
CREATE TABLE CURRENCY
(
  ID            BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_58989CC5_B2C3_45EF_8159_F985ACE2AC38) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  CODE          VARCHAR(255),
  EXCHANGE_RATE DOUBLE
);
CREATE UNIQUE INDEX UK_H84PD2RTR12ISNIFNJ655RKRA_INDEX_5
  ON CURRENCY (CODE);
CREATE TABLE PRODUCT
(
  ID          BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_A2122776_3A68_459F_AA96_7F9BC186FC30) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  PRICE       DOUBLE,
  CURRENCY_ID BIGINT                                                                                                                 NOT NULL,
  CONSTRAINT FKJS3QD4L0EBV5A0JFO7V59IMBN FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY (ID)
);
CREATE TABLE SALE
(
  ID          BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_0A805404_B28D_43BC_94DF_918A065AE97C) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  END_TIME    TIMESTAMP,
  ITEMS_LEFT  INTEGER,
  START_TIME  TIMESTAMP,
  TOTAL_ITEMS INTEGER,
  COUNTRY_ID  BIGINT,
  PRODUCT_ID  BIGINT                                                                                                                 NOT NULL,
  CONSTRAINT FKDF71JEAXL0EQRH1AB0WIET7JJ FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (ID),
  CONSTRAINT FKONRCQWF09U6SPB6TY6SH11JH5 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);
CREATE TABLE USER
(
  ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_24D2D938_C022_43BF_9D62_C0003B650D74) AUTO_INCREMENT PRIMARY KEY NOT NULL
);
CREATE TABLE WALLET
(
  ID          BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_D92A5977_F895_466D_8DBB_AD359A38D020) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  BALANCE     DOUBLE,
  CURRENCY_ID BIGINT,
  USER_ID     BIGINT                                                                                                                 NOT NULL,
  CONSTRAINT FKHWM501SBBOC7ALNO0GI3CFA86 FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY (ID),
  CONSTRAINT FKBS4OGWIKNSUP4RPW8D47QW9DX FOREIGN KEY (USER_ID) REFERENCES USER (ID)
)
