INSERT INTO PUBLIC.WALLET (ID, BALANCE, CURRENCY_ID, USER_ID) VALUES (1, 0, 1, 1);
INSERT INTO PUBLIC.WALLET (ID, BALANCE, CURRENCY_ID, USER_ID) VALUES (2, 9999, 1, 2);
INSERT INTO PUBLIC.WALLET (ID, BALANCE, CURRENCY_ID, USER_ID) VALUES (3, 1, 1, 3);